#!/usr/bin/env python

from argparse import ArgumentParser
import os
import subprocess
import re
import sys
import pipes

CPU_COMPILER = ('/usr/bin/ar')

def main():

  cpu_compiler_flags = [flag for flag in sys.argv[1:]]
  for index, flag in enumerate(cpu_compiler_flags):
    if 'rcsD' in flag:
      cpu_compiler_flags[index] = 'rcs'
  return subprocess.call([CPU_COMPILER] + cpu_compiler_flags)

if __name__ == '__main__':
  sys.exit(main())
